### ISSUE TITLE
wiki_folder does not find visible folder

### ISSUE THREAD

**Issue by MrHinsh** [JoeIzzard/action-wiki-sync#1]
The system does not detect the "docs" folder that I have in the route... is my format correct?

Docs Folder: https://github.com/nkdAgility/azure-devops-migration-tools/tree/master/docs

```
name: Wiki Sync

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: JoeIzzard/ghaction-wiki-sync@v1
      with:
        # The username of the repo owner
        username: MrHinsh
        access_token: "{{ secrets.GITHUB_TOKEN }}"
        wiki_folder: "docs"
        commit_message: "Update Wiki"
        commit_username: "MrHinsh"
        commit_email: "martin@nkdagility.com"
```

**Comment by JoeIzzard** [comment]
It's been a little while since I last used this, so I may be missing something myself.

The settings for the wiki sync action looks good, but it does require a checkout first. Not sure if this is an exact copy of what you were trying or not, but it should first use the checkout before using my sync action like below.

```
name: Wiki Sync

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: JoeIzzard/ghaction-wiki-sync@v1
      with:
        # The username of the repo owner
        username: MrHinsh
        access_token: "{{ secrets.GITHUB_TOKEN }}"
        wiki_folder: "docs"
        commit_message: "Update Wiki"
        commit_username: "MrHinsh"
        commit_email: "martin@nkdagility.com"
```

Hope that get you syncing!
